### ISSUE TITLE
entity_alignment 的内存需求问题

### ISSUE THREAD

**Issue by yeung66** [nju-websoft/NJU_KnowledgeFusionCourseExp#1]
想问问 entity_alignment 中的那个 baseline 方法 MTransE 到底需要多少内存才能够正常运行呢？
似乎即使我租了 96G 的服务器运行也会内存不够

**Comment by yeung66** [comment]
![image](https://user-images.githubusercontent.com/22522618/126615306-9b869168-7928-4dbf-a3ad-ec14af4bb301.png)

**Comment by sunzequn** [comment]
同学你好，

我刚刚测试了一下，我本地大概使用了60g左右的内存，但是可能会随着训练进行逐渐增加。我后面优化一下代码。

![image](https://user-images.githubusercontent.com/5676248/126635645-42e1422f-ea4a-441b-a00a-eba7bc1fc883.png)

你先完成其他实验任务，或者你先把构造neighbors的代码注释掉来测试模型。
